server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jorgdz/config-centralized.git
          #skip-ssl-validation: true
          #username: usuario
          #password: clave