management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: us-enviarEmail
  config:
    import: optional:configserver:http://${SERVER_CONFIG}:8888/
   
  profiles:
    active: ${SPRING_PROFILE}